### ISSUE TITLE
BLS test vectors

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-tests#6]
Ref: https://github.com/ethereum/py-evm/blob/master/eth/_utils/bls.py

- [ ] `aggregate_pubkeys(pubkeys: Sequence[int]) -> int`
- [ ] `verify(message: bytes, pubkey: int, signature: bytes, domain: int) -> bool`
- [ ] `verify_multiple(verify_multiple(pubkeys: Sequence[int], messages: Sequence[bytes], signature: bytes, domain: int) -> bool`

@mratsim Anything else I missed?

**Comment by mratsim** [comment]
No it's perfect for a start (with the addition of `sign` and `aggregate_signatures` from the file)

Later there will be the proof of possessions.

**Comment by cheatfate** [comment]
It would be very helpful to have test vectors in binary (hexadecimal) form in tuples like this:
([`Private Key`], [`Public Key`], [`Plain text`], [`Signature`], [`Result`]).

In such way you can check this operations:
1. Private Key serialization and deserialization.
2. Private Key -> Public Key
3. Public Key serialization and deserialization.
4. hashToG2(`Plain text`).
5. Signature creation process
6. Signature serialization and deserialization.
7. Signature verification.

**Comment by djrtwo** [comment]
closed via #12 / #13
