### ISSUE TITLE
Reminder: avoid Eth1 mistakes

### ISSUE THREAD

**Issue by mratsim** [ethereum/eth2.0-tests#9]
Continuation from https://github.com/status-im/eth2-testgen/issues/1#issuecomment-448142854

One mistake that was done in Eth1 was having all tests available directly in the repo.
This led to [hard-to-review PRs with 8k lines changed](https://github.com/ethereum/tests/pull/497/files) to [unreviewable PRs with 1M lines changed](https://github.com/ethereum/tests/pull/511/files).

### Proposition

Keep small subsets of tests in yaml files in the repo as it allows easy inspection and promotes discussion, but complete tests should be generated during CI by Travis/Appveyor.

**Comment by jannikluhn** [comment]
How would a project than checkout those tests? Currently, they can be used as Git Submodules which is quite convenient, but if the tests are generated by CI this doesn't seem possible anymore.

A compromise might be to generate and commit the tests locally, but also check during CI that the tests have been generated correctly (by generating them again and comparing the result). Then reviewers could ignore the 1M changed lines and focus on the 10 that caused the rest to change.

**Comment by mratsim** [comment]
Yes that's one big tradeoff.

Maybe have a repo generated tests, with merged PRs in eth2.0-tests automatically submitting and merging new test files to eth2.0-tests-generated?

**Comment by jannikluhn** [comment]
> Maybe have a repo generated tests, with merged PRs in eth2.0-tests automatically submitting and merging new test files to eth2.0-tests-generated?

:+1: Good idea

Even the same repository should be fine, as long as it's automatized. I looked a little bit into CircleCI and this kind of stuff seems to be possible with it. Whenever a PR is merged, they can build the tests, commit them directly to master and if desired make a new release.

**Comment by ChihChengLiang** [comment]
Support generate in a different repository because it is very likely slow to clone.

To do an automatic Github push, generate a Github user key on Circle CI website and configure a push command in `.circleci/config.yml`. [doc](https://circleci.com/docs/2.0/gh-bb-integration/)

**Comment by hwwhww** [comment]
Here you are:
https://github.com/ethereum/eth2.0-tests-generators

Let me know if you'd like to rename it.
